
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

export const generateThumbnail = async (title: string, headshotBase64: string): Promise<string> => {
  try {
    const model = 'gemini-2.5-flash-image';
    
    // Clean base64 string
    const base64Data = headshotBase64.split(',')[1] || headshotBase64;

    const prompt = `
      TASK: Create a professional, high-quality YouTube Shorts vertical thumbnail (1080x1920, 9:16).
      
      TITLE TO RENDER: "${title}"
      
      SUBJECT:
      - Use the person from the provided headshot as the main subject.
      - Generate a realistic upper-body portrait (head, shoulders, chest, and arms).
      
      ANATOMY & POSTURE (CRITICAL):
      - Hands must be fully visible, natural, and anatomically correct (strictly 5 fingers per hand, correct proportions).
      - Natural human posture: relaxed body alignment, no twisted joints, no extra limbs, no distorted joints.
      - Pose and facial expression must perfectly match the emotion of the title "${title}".
      - Potential poses based on title: pointing (if motivational/tips), thinking pose (if focus/study), surprised/open hands (if shock), or confident crossed arms.
      - NO robotic or stiff postures.
      
      VISUAL QUALITY:
      - Ultra-realistic human anatomy and natural skin textures.
      - Cinematic lighting: Studio-quality soft shadows with vibrant rim lighting/glow highlights.
      - Sharp subject focus with cinematic depth of field (blurred background related to the video topic).
      - Professional YouTube creator aesthetic: high contrast, vibrant "scroll-stopping" colors.
      
      TYPOGRAPHY:
      - Render the title using bold, modern, high-contrast 3D typography.
      - Text MUST be clean, readable, and optimized for mobile viewing.
      - Use a maximum of 2-5 words for the text to ensure impact.
      - SMART PLACEMENT: Do NOT overlap the face or hands. Place text in clear areas (top third or center).
      
      NEGATIVE CONSTRAINTS (STRICT):
      - No extra fingers or distorted hands.
      - No artificial or deformed limbs.
      - No floating arms or unnatural body posture.
      - No cartoonish, AI-distorted, or low-quality look.
      - No blurry hands or faces.
      - No cropped hands or arms at the edge.
    `;

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: 'image/jpeg',
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "9:16",
        },
      },
    });

    let imageUrl = '';
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      for (const part of candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return imageUrl;
  } catch (error) {
    console.error("Gemini Service Error:", error);
    throw error;
  }
};
